{
 "title": "Homework",
 "time": { "from": "2024-02-29T19:00:00.000Z", "to": "2024-03-31T18:59:59.000Z" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "homework",
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "homework",
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "homework",
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Fare Amount",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dataset": "homework",
     "rawSql": "SELECT \"timestamp\", fare_amount FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}