channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.0
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==2.3.3
  - pandas==2.2.3
  - psutil==5.9.0
  - scikit-learn==1.6.1
  - scipy==1.16.2
name: mlflow-env
